[[ESP]]
arch = "x86_64"
git-tree-sha1 = "59f66340fcebcd3af235e4ea33bc76c29be247d3"
libc = "glibc"
os = "linux"

    [[ESP.download]]
    sha256 = "de55698ef2c4d99ab2d0c4ab1e1e6c690feb4da3c26b7ca42f1805b5e8b88926"
    url = "https://github.com/cmhamel/ESP_jll.jl/releases/download/ESP-v1.23.0+0/ESP.v1.23.0.x86_64-linux-gnu.tar.gz"
