# Autogenerated wrapper script for ESP_jll for x86_64-linux-gnu
export libcaps, libegads, libocsm, serveCSM

using CompilerSupportLibraries_jll
using XML2_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("ESP")
JLLWrappers.@declare_library_product(libcaps, "libcaps.so")
JLLWrappers.@declare_library_product(libegads, "libegads.so")
JLLWrappers.@declare_library_product(libocsm, "libocsm.so")
JLLWrappers.@declare_executable_product(serveCSM)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, XML2_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libcaps,
        "ESP128/EngSketchPad/lib/libcaps.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libegads,
        "ESP128/EngSketchPad/lib/libegads.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libocsm,
        "ESP128/EngSketchPad/lib/libocsm.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        serveCSM,
        "ESP128/EngSketchPad/bin/serveCSM",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
